### ISSUE TITLE
How can view rtsp camera CCTV or camera IP?

### ISSUE THREAD

**Issue by guytechNet** [victor-david/camera-eye#13]
Hi Mr. Victor David,

 I can not view rtsp camera CCTV or camera IP after I added and configured, drag it to the display position I want.

Can you help me?

**I added and configured**
![Screenshot 2023-06-08 150721](https://github.com/victor-david/camera-eye/assets/118602474/d3225249-7379-4dd1-9a5a-0752088ba2d0)

**drag it to the display position I want**
![Screenshot 2023-06-08 150609](https://github.com/victor-david/camera-eye/assets/118602474/c1e0b046-2fb4-40d1-8cd2-489d256604ce)

**Comment by victor-david** [comment]
Hi, you must select a plugin. On your screenshot, no plugin is selected. There are three plugins as part of the code, and the idea was that people could develop their own for other cameras.

Also, the IP address should be simply the ip, not a url. The plugin takes care of constructing a url appropriate for the camera the plugin is designed for.

I wrote three plugins with the app because that's what kind of cameras I have/had access to.

**Comment by guytechNet** [comment]
Hi Mr. Victor David,

I saw you written at readme.md (red line -> Supports RTSP and MJPEG but I can not use it your project) 
![Screenshot 2023-06-12 100116](https://github.com/victor-david/camera-eye/assets/118602474/2fba84d2-a3ed-4785-88d9-e35d7985eb0e)
Do you miss plugin RTSP and MJPEG?

**Comment by victor-david** [comment]
Are you saying that there are no plugin options in the drop down list on the camera settings? Because of the nature of how plugins work, after a build, they must be copied into the Plugins directory. This is handled by **PostBuild.cmd** 

https://github.com/victor-david/camera-eye/blob/master/src/Camera.App/PostBuild.cmd

Also, you'd need to follow what it says here about Ffmpeg: 

https://github.com/victor-david/camera-eye/blob/master/src/Camera.App/Ffmpeg/README.md

**Comment by guytechNet** [comment]
Hi victor david,
I have *.dll plugin as follow
![Screenshot 2023-06-12 133850](https://github.com/victor-david/camera-eye/assets/118602474/eb0495bd-fdf6-4c6e-ac30-5afd4608884a)
And plugin saw at box as 
![Screenshot 2023-06-12 133747](https://github.com/victor-david/camera-eye/assets/118602474/e76be2f7-0154-4e5e-bb67-dddbf750e137)
But my rtsp do not working at your Cam Eye, however it work at RtspClientSharp project.
What's happen?

**Comment by victor-david** [comment]
There's a couple of things to keep in mind:
1. Make sure you've [installed the FFMPEG](https://github.com/victor-david/camera-eye/blob/master/src/Camera.App/Ffmpeg/README.md)  .dlls. They are not in the project.  After build, one level up from Plugins, along with the main .exe, you should see avcodec-58.dll, avdevice-58.dll, avfilter-7.dll, etc. 
2.  Make sure you've selected a Plugin. I don't know what camera you have. An appropriate plugin might not be included. If not, you can create one if you want to.
3.  According to your latest screenshot, you've still got a URL in the ip address field. It should be only the IP.

**Comment by guytechNet** [comment]
Hi Mr. Victor David,
I saw you written at readme.md (red line -> **Supports RTSP and MJPEG but I can not use it your project**)
![245003612-2fba84d2-a3ed-4785-88d9-e35d7985eb0e](https://github.com/victor-david/camera-eye/assets/118602474/19a5b57e-9564-4338-b3ef-f3359908ba0e)
**Did you miss a plugin RTSP link in your project?** Please help me plugin RTSP!

**Comment by victor-david** [comment]
Yes, the app supports RTSP and MJPEG in the underlying transport protocols. The underlying protocols are used by a plugin, which is designed for a certain type of camera. In an attempt to help, I've posed various questions and suggestions for you, and also pointed out what was wrong with your config screen, but haven't received any answers as to whether you followed those suggestions. It is _mandatory_ to:

1. Select a plugin
2. Use only an ip address, not a URL
3. Install the ffmpeg .dlls

And once again, the plugins that are included may not work for your camera. That's why it's a plugin architecture, so others can develop plugins for other cameras.
